/**
 * This class is generated by jOOQ
 */
package com.model;


import com.model.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpringcloudTemplate extends SchemaImpl {

    private static final long serialVersionUID = -540443092;

    /**
     * The reference instance of <code>springcloud-template</code>
     */
    public static final SpringcloudTemplate SPRINGCLOUD_TEMPLATE = new SpringcloudTemplate();

    /**
     * The table <code>springcloud-template.users</code>.
     */
    public final Users USERS = com.model.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private SpringcloudTemplate() {
        super("springcloud-template", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Users.USERS);
    }
}
