/**
 * This class is generated by jOOQ
 */
package com.model;


import com.model.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in springcloud-template
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>springcloud-template.users</code>.
     */
    public static final Users USERS = com.model.tables.Users.USERS;
}
